logging:
  level:
    com:
      xbang:
        bootdemo: info
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

server:
  port: 8080

spring:
  application:
    name: boot-demo
  cache:
    type: redis
    redis:
      use-key-prefix: true
      key-prefix: redis-key


  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Soar18786611964
    url: jdbc:mysql://47.104.171.254:3306/user-provider?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull&useSSL=false


mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.xbang.bootdemo.dao.entity
  #typeEnumsPackage: com.baomidou.springboot.entity.enums
  configuration:
    cache-enabled: true



