logging:
  level:
    com:
      xbang:
        bootdemo: trace
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

server:
  port: 8080